"use strict";

var all_bubbles = {
    20: {
        x: 937.333333333333,
        y: -5266.833333333333,
        r: 100,
        link: [],
        title: "Editing",
        facts: "Check out the help menu in the top right corner of the screen.\n<br>\nYou can put arbitrary html (images, links, ...) in these boxes. We also support latex using <a href=\"https://www.mathjax.org/\">MathJax</a>.  We use the $$\\$\\$$$ quotes to start a mathjax context. Here is an example:\n<br>\n$$ \\frac{\\partial c}{\\partial t} = e^{-t} $$\nAfter you're done editing, you've only really edited the graph locally. Nobody else who visits this website will see your edits.<br>If you want to publicize your edits, press 'g' (this creates a data file), and send it to the developers, or visit us on <a href=\"https://github.com/BourgondAries/hmm\">github</a> and open up a pull request of leave an issue.\n<br>\n<br>\nContact us at any of these addresses:\n<br>\n<a href=\"mailto:macocio@gmail.com\">macocio@gmail.com</a><br>\n<a href=\"mailto:kevinrs@stud.ntnu.no\">kevinrs@stud.ntnu.no</a>\n",
    },
    21: {
        x: -1077.8571428571431,
        y: -12806.948979591836,
        r: 100,
        link: [],
        title: "Modulo",
        facts: "The operation used to find the remainder is called the modulo operation. The remainder is sometimes called the modulus. <br> \n<br>\n<span style=\"font-weight: bold;\">Notation:</span> <br>\nExample: <br>\n$$1 \\equiv 4 \\mod{3}$$\nGenerally it looks like this: <br>\n$$r \\equiv a \\mod{n}$$\n\na is called the dividend and a the divisor. <br>\n\n<br>\n<span style=\"font-weight: bold;\">Note:</span> \nThere are different definitions for negative dividends, depending on tool for calculation. <br>\n<br>\n<span style=\"font-weight: bold;\">Uses:</span> <br>\nThe modulo operation is sometimes used in programming. The most basic use of this operation is to find whether a number (the dividend) is an odd or even number. Simple use 2 as the divisor and see if the modulus is 1 (odd) or 0 (even). <br>\n<br>\nModulo is also used in cryptography and hashing.",
    },
    22: {
        x: 1580.780238924839,
        y: -12684.650323544047,
        r: 100,
        link: ["28", "integer_mul"],
        title: "Exponents",
        facts: "Exponents is a notation for repeated multiplication. <br>\n<span style=\"font-weight: bold;\">Example:</span> <br>\n$$5\\times 5\\times 5\\times 5$$\nIt takes a lot of space, but thanks to exponents we can write the same thing as: <br>\n$$5^4$$\n5 is called the base and 4 the exponent. <br>\nAnother example:\n$$3\\times 3\\times 3$$\nis the same as\n$$3^3$$\nand this is the same as\n$$9$$\n<span style=\"font-weight: bold;\">General notation looks like:</span> <br>\n$$b^a$$\nAgain here b is the base and a the exponent.\nThis means we calculate\n$$b \\times b \\times b \\times ... \\times b$$ 'a' times.",
    },
    23: {
        x: 940.7802389248391,
        y: -13124.650323544047,
        r: 100,
        link: ["integer_mul"],
        title: "Square root",
        facts: "If you 'take' the square root of a number, you find a new number which if you multiply it with itself, you get the number you started with. <br>\n<span style=\"font-weight: bold;\">Example:</span> <br>\n$$\\sqrt{4} = 2$$\nBecause: <br>\n$$2 \\times 2 = 4$$",
    },
    24: {
        x: -434.4795918367354,
        y: -14912.173469387759,
        r: 100,
        link: ["38"],
        title: "nth root",
        facts: "You have learned about the square root, in that case n was 2. But n doesn't have to be 2, it can be any positive integer. <br>\n<br> If we ask ourselves what is the nth root of a number? It is another number which is you multiply is by itself n times you get the number you started with.\n$$\\sqrt[4]{16} = 2$$\nBecause:\n$$2 \\times 2 \\times 2 \\times 2 = 16$$\nor if we use eponentials:\n$$2^4 = 16$$\nGenerally:\n$$r^n = x$$\nr is the nth root of x.",
    },
    25: {
        x: -346.4795918367354,
        y: -14368.173469387759,
        r: 100,
        link: [],
        title: "Decimal power",
        facts: "We know what it means to find the nth root or calculate an exponential with a positive whole number. But can we do the same with a decimal number?<br>\nWhat does the following equal?\n$$ 5^{2.5} $$  \n\nRemember that\n\n$$ 5^2 = 5 \\times 5 $$\n\nHowever, with the added 0.5, we can simply multiply with the square root:\n\n$$ 5^{2.5} = 5^2 \\times 5^{0.5} = 5 \\times 5 \\times \\sqrt{5} $$",
    },
    26: {
        x: 600.7802389248391,
        y: -13458.650323544047,
        r: 100,
        link: ["rationals", "23", "29"],
        title: "Irrationals",
        facts: "Irrational numbers are numbers that can not be represented by a fraction like\n\n$$ \\frac{103}{7} $$\n\nAn example of an irrational number is\n\n$$ \\sqrt{2} \\approx 1.414 $$\n\n<span style=\"font-weight: bold;\">Proof:</span>\nLet's suppose $$\\sqrt{2}$$ is a rational number. Then we can write it $$\\sqrt{2}  = \\frac{a}{b}$$ where a, b are whole numbers, b not zero.\n<br><br>\nWe additionally assume that this a/b is simplified to lowest terms, since that can obviously be done with any fraction. Notice that in order for a/b to be in simplest terms, both of a and b cannot be even. One or both must be odd. Otherwise, we could simplify a/b further.\n<br><br>\nFrom the equality $$\\sqrt{2} = \\frac{a}{b}$$ it follows that $$2 = \\frac{a^2}{b^2}$$  or  $$a^2 = 2 \\cdot b^2$$.  So the square of a is an even number since it is two times something.\n\nFrom this we know that a itself is also an even number. Why? Because it can't be odd; if a itself was odd, then a · a would be odd too. Odd number times odd number is always odd.\n\nIf a itself is an even number, then a is 2 times some other whole number. In symbols, a = 2k where k is this other number. We don't need to know what k is; it won't matter. Soon comes the contradiction.\n\nIf we substitute a = 2k into the original equation $$2 = \\frac{a^2}{b^2}$$, this is what we get:\n\n$$2    =    (2k)^2/b^2$$\n$$2    =    4k^2/b^2$$\n$$2\\cdot b^2    =    4k^2$$\n$$b^2    =    2k^2$$\nThis means that b2 is even, from which follows again that b itself is even. And that is a contradiction.",
    },
    27: {
        x: 12.780238924839068,
        y: -13772.650323544047,
        r: 100,
        link: ["26", "rationals", "29"],
        title: "Real",
        facts: "Real numbers contain both rational and irrational numbers. An irrational number is never rational, and a rational number is never irrational. A real number can be either rational or irrational.",
    },
    28: {
        x: 1086.780238924839,
        y: -13650.650323544047,
        r: 100,
        link: ["30"],
        title: "Polynomials",
        facts: "Polynomials are expressions. Here is an example of a polynomial:\n\n$$ x^2 + 4\\cdot x - 2 $$\n\nYou can put a number into x, and the polynomial will become another number.\n<br><br>\nIf x is 2:\n\n$$ 2^2 + 4\\cdot 2 - 2 $$\n\nWhich becomes\n\n$$ 4 + 8 - 2 $$\n$$ \\Rightarrow 10 $$\n\nPolynomials can have any natural number exponent:\n\n$$ 54\\cdot x^{143} + \\frac{73}{3}\\cdot x^3 + 94 $$\nis a valid polynomial.",
    },
    29: {
        x: 488.78023892483907,
        y: -14544.650323544047,
        r: 100,
        link: ["31"],
        title: "Transcendentals",
        facts: "Transcendental numbers are numbers that can not be the root of a polynomial.\n<br><br>\nYou can not find any polynomial that has a root that is a transcendental number.\n\n<span style=\"font-weight: bold;\">Example:</span>\n<br>\nThis number is called 'pi', pronounced \"pie\". It is very important. You will use it later. You will use it a lot.\n$$ \\pi \\approx \\frac{355}{113} \\approx 3.141593 $$\nAnother number that is transcendental and extremely important is Euler's Number:\n$$ e \\approx 2.71828 $$",
    },
    30: {
        x: 1024.780238924839,
        y: -14412.650323544047,
        r: 100,
        link: ["29"],
        title: "Polynomial Root",
        facts: "The root of a polynomial denotes the following:\n\nRemember: A polynomial is an <span style=\"font-weight: bold;\">expression</span> like\n$$ x^2 + 4\\cdot x - 2.25 $$\n\nWhen you say \"The root of a polynomial\", you mean \"the x value that will turn the expression into 0\":\n\n$$ x^2 + 4\\cdot x - 2.25 = 0 $$\n\nWhat is the x value to make the equation true?\n<br>\n<br>\nLet's try x = 0.5:\n$$ 0.5^2 + 4\\cdot 0.5 - 2.25 = 0 $$\n$$ \\Rightarrow 0.25 + 2 - 2.25 = 0 $$\n$$ \\Rightarrow 2.25 - 2.25 = 0 $$\n$$ \\Rightarrow 0 = 0 $$\n\nWe see that 0.5 works as a root! 0.5 is the root of this polynomial.",
    },
    31: {
        x: -43.21976107516093,
        y: -14972.650323544047,
        r: 100,
        link: ["28", "27"],
        title: "Complex",
        facts: "Complex numbers are not complicated or 'complex' in difficulty. They are easy.\n\nSuppose you have a polynomial\n$$ x^2 + 1 $$\n\nWhat is the root of this polynomial?\n\n$$ x^2 + 1 = 0 $$\n$$ \\Rightarrow x^2 = -1 $$\n$$ x = \\sqrt{-1} $$\n\nThe square root of a negative number makes no sense. To make sense of it, we use complex numbers. We claim that:\n\n$$ \\sqrt{-1} = i $$\n\n'i' is the complex unit, as '1' is the unit in other numbers.\n<br>\nThe root of the polynomial is:\n\n$$ 0 + i $$\n\nComplex numbers have a 'real' and 'complex' part.",
    },
    32: {
        x: 1420.780238924839,
        y: -14024.650323544047,
        r: 100,
        link: ["33"],
        title: "Degree",
        facts: "The degree of the polynomial is the number that is the largest exponent.\n\n$$ x^4 + x^3 - 3 $$\n\nis a polynomial of degree 4.\n\n$$ x^8 + x^93 - 94 $$\n\nis a polynomial of degree 93. 94 is not an exponent.",
    },
    33: {
        x: 1688.780238924839,
        y: -14368.650323544047,
        r: 100,
        link: ["30"],
        title: "Equations",
        facts: "An equation is an assertion of fact. We use the '=' symbol for equations.\n\n$$ 1+2 = 3 $$\n\nThe above is a fact. It is always true, even if both sides look different.\n<br>\nYou can write\n\n$$ x + 3 = 0 $$\n\nWhat does x need to be for the equation to be true?\n\n$$ x = -3 $$\n\nBecause\n\n$$ (-3) + 3 = 0 $$",
    },
    34: {
        x: 1068.5,
        y: -15293.5,
        r: 100,
        link: ["32", "33", "30"],
        title: "1. Polynomial",
        facts: "Sometimes we have a polynomial. The order of the polynomial is 1.\n\n$$ x + 3 $$\n\nTo find the root, we ass ' = 0':\n\n$$ x + 3 = 0 $$\n\nFirst order polynomials can easily be solved for 'x'. You first add or subtract to remove the term:\n\n$$ x + 3 - 3 = -3 $$\n\nYou subtract 3 from both sides\n\n$$ x + (3 - 3) = -3 $$\n$$ \\Rightarrow x + (0) = -3 $$\n$$ \\Rightarrow x = -3 $$\n\nWe have now solved the root of the polynomial. It is $$-3$$\n\nIf you have a polynomial with a multiplier:\n\n$$ 43\\cdot x + 3 = 0 $$\n\nFirst, you remove the <span style=\"font-weight: bold;\">term</span>: (3) is the term.\n\n$$ 43\\cdot x + 3 - 3 = -3 $$\n$$ \\Rightarrow 43\\cdot x + (3-3) = -3$$\n$$ \\Rightarrow 43\\cdot x + (0) = -3$$\n$$\\Rightarrow 43\\cdot x = -3$$\n\nNow you can divide both sides by 43:\n\n$$\\Rightarrow \\frac{43}{43}x = \\frac{-3}{43} $$\n$$\\Rightarrow x = \\frac{-3}{43}$$\n\nWe have now solved the root.",
    },
    35: {
        x: 174.5,
        y: -15763.5,
        r: 100,
        link: ["34"],
        title: "2. Polynomial",
        facts: "The second order polynomial is more difficult to find the root for. Here is an example of a second order polynomial:\n\n$$ 3x^2 + 5x + 2 $$\n\nTo find the root, we add '= 0':\n\n$$ 3x^2 + 5x + 2 = 0 $$\n\nWe have to <span style=\"font-weight: bold;\">remember</span> the equation\n\n$$ x = \\frac{-b \\pm \\sqrt{b^2-4ac}}{2a} $$\n\nThis says: \"The root (x) is the right side of the = sign\".\n\nWhat do a, b, and c mean? The root equation is assumed to be of the form:\n\n$$ a\\cdot x^2 + b\\cdot x + c = 0 $$\n\nWe see that:\n\n$$ a = 3, b = 5, c = 2 $$\n\nWe can put these number into the equation and get:\n\n$$ x_1 = \\frac{-5+\\sqrt(1)}{6}$$\n$$ \\Rightarrow x_1 = \\frac{-4}{6} = \\frac{-2}{3}$$\n$$ x_2 = \\frac{-5-\\sqrt(1)}{6}$$\n$$ \\Rightarrow x_2 = \\frac{-6}{6} = -1$$\n\nNote the\n\n$$\\pm$$\n\nThis means that there will be two roots! In fact, an polynomial of second order has two roots!\n<br>\nHow many roots do you think a polynomial of third order has?",
    },
    36: {
        x: -1176.8469387755104,
        y: -13706.683673469386,
        r: 100,
        link: ["26", "37"],
        title: "Right Triangle",
        facts: "A right triangle is any triangle with a corner that is exactly $$90^\\circ$$\n\n<img src=\"Textures/small-right-triangle.png\">\n\nWe use a square to point out where that corner is.\n\n<img src=\"Textures/small-right-triangle-noted.png\">\n\nHere, a, b, and c mean the <span style=\"font-weight: bold;\">lengths</span> of the sides.\n<br>\nA, B, and C mean the <span style=\"font-weight: bold;\">angles</span> of the corners.\n<br>\n\nWe see that C is 90 degrees.",
    },
    37: {
        x: -662.8469387755104,
        y: -14182.683673469386,
        r: 100,
        link: [],
        title: "Pythagorean Theorem",
        facts: "The Pythagorean theorem is an ancient triangle theorem.\nA theorem is to be considered an \"eternal truth\". It can never be broken. It is impossible.\n\n<img src=\"Textures/small-right-triangle-noted.png\">\n\n<br>\n<span style=\"font-weight: bold;\">Theorem:</span>\n$$ c^2 = a^2 + b^2 $$\n\nThis can be rewritten as \n\n$$ c = \\sqrt{a^2 + b^2} $$\n\nThis means that having two of the a, b, c numbers, you can calculate the other one. This is <span style=\"font-weight: bold;\">only for right triangles</span> (with a 90 degree corner).",
    },
    38: {
        x: -607.8129251700689,
        y: -14592.173469387759,
        r: 100,
        link: ["27", "25"],
        title: "Power-Add rule",
        facts: "Multiplying the same bases 'b' of different powers allows us to simply add the powers.\n\nRemember that a base of power 'p' is given as:\n\n$$ b^p $$\n\nIf we multiply two numbers of base 5, both with different powers:\n\n$$ 5^4 \\times 5^6 $$\n\nThis number is simply\n\n$$ 5^{4 + 6} = 5^{10} $$",
    },
    start: {
        x: 0,
        y: 0,
        r: 100,
        link: ["music"],
        title: "Click here!",
        facts: "Welcome to 'Hmm', the sanctuary of mathematics! To get started, you can drag yourself anywhere using the mouse. The arrow keys, 'wasd', or 'hjkl' can also be used.",
    },
    music: {
        x: 0,
        y: -1000,
        r: 100,
        link: ["fullscreen"],
        title: "Music",
        facts: "To change the mute state of music and sounds, press 'm'. You can also click the top-left music button.",
    },
    fullscreen: {
        x: 0,
        y: -2000,
        r: 100,
        link: ["zoom"],
        title: "Fullscreen",
        facts: "'Hmm' is best enjoyed in full screen. Most browsers support this. Press F11 to enter or exit fullscreen mode.",
    },
    zoom: {
        x: 0,
        y: -3000,
        r: 100,
        link: ["mouseless"],
        title: "Zoom",
        facts: "You can use the +/- buttons or the scroll wheel to zoom in our out.",
    },
    mouseless: {
        x: 0,
        y: -4000,
        r: 100,
        link: ["goal"],
        title: "Mouseless",
        facts: "You can select a node if it's centered, press the space bar to open and any move to close the info window.",
    },
    goal: {
        x: 0,
        y: -5000,
        r: 100,
        link: ["devmode", "numbers", "20"],
        title: "Goal",
        facts: "Your goal is to dive deep into the beauty of mathematics, or not. It's up to you, and you alone.",
    },
    devmode: {
        x: 1500,
        y: -5000,
        r: 100,
        link: [],
        title: "Dev-mode",
        facts: "A little more information is available by pressing 'e'. This opens up 'Developer mode'. It just shows you your current position and the mouse position.",
    },
    numbers: {
        x: 0,
        y: -10000,
        r: 100,
        link: ["natural_numbers", "number_system"],
        title: "Numbers",
        facts: "Numbers are mathematical objects. A number can represent a quantity, they can be used as labels, for ordering of objects or measuring. There are many types of numbers. '1' is a number. '9.8' is also a number. Not all numbers can be written only with the use of 0, 1, 2, 3, 4, 5, 6 ,7, 8, 9. You will learn about these number later. <br>\n<br>\nNumbers where invented thousands of years ago, but did you know that the number 0 was invented relativly more recently.",
    },
    number_system: {
        x: 600,
        y: -10500,
        r: 100,
        link: [],
        title: "Number System",
        facts: "The decimal number system is made up of ten symbols: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0. The least significant digit is the rightmost digit. This means that 10 is greater than 1. When we compare, we can pad digits so they become the same length. 10 and 1 can be seen as 10 and 01. A zero to the left does not change the number. A zero to the right does change the number.",
    },
    natural_numbers: {
        x: 161.33333333333212,
        y: -10818.833333333332,
        r: 100,
        link: ["natural_numbers_addition", "natural_numbers_subtraction", "integers"],
        title: "Natural Numbers",
        facts: "Natural numbers are whole numbers. They do not have a '.' in the number. $$10$$ is natural number. $$8932$$ is a natural number. $$-3$$ is not a natural number, because it has a minus sign (-). $$5.5$$ is not a natural number because it contains a dot '.'.\n<br>\n<br>\nThis picture shows the natural number line. It never ends to the right.\n<img src=\"Textures/number-line-positive.gif\">",
    },
    natural_numbers_addition: {
        x: -334.6666666666679,
        y: -10770.833333333332,
        r: 100,
        link: ["natural_multiplication"],
        title: "Addition",
        facts: "You can add natural numbers together. This creates a new number. The symbol for adding is '+' (called plus). You put two natural numbers on either side of the plus: 3 + 4. The expression 3 + 4 is the same as the number 7.",
    },
    natural_numbers_subtraction: {
        x: -365.21976107516093,
        y: -11742.650323544047,
        r: 100,
        link: ["integers", "integer_division"],
        title: "Subtraction",
        facts: "You can subtract natural numbers. This creates a new number. The symbol for subtracting is '-' (called minus). You put two natural numbers on either side of the minus: $$4 - 3$$ The expression $$4 - 3$$ is the same as the number $$1$$ The expression $$10 - 2$$ is the same as the number $$8$$",
    },
    integer_division: {
        x: -14.66666666666788,
        y: -12482.833333333332,
        r: 100,
        link: ["remainder", "rationals"],
        title: "Division",
        facts: "We divide using the '/' symbol. Two integers on either side can create a new number. The left side is the 'numerator', and the right side is the 'denominator'. The expression 6 / 2 is the same as 3, and integer and natural number. The expression -8 / 2 is the same as -(8 / 2), which is the same as - ( 4 ), which is the same as -4, an integer. What does division mean? It means how often can we subtract the denominator from the numerator until it becomes zero? From 6 we can subtract 2, three times: 6 / 2 is the same as 3. The expression 6 - 2 - 2 - 2 becomes 0.",
    },
    rationals: {
        x: 457.3333333333321,
        y: -12818.833333333332,
        r: 100,
        link: [],
        title: "Rationals",
        facts: "You have seen integer division. What if the subtraction of the denominator from the numerator doesn't go to 0? Remember that with the expression 6 / 2, we subtract the right side from the left side (of the / sign) until the left side is 0. What if we have something like $$\\frac{5}{2}$$ Let's try: $$5 - 2 = 3$$ Now we have $$3$$ Next: $$3 -  2 = 1$$ If we subtract 2 once again, we get -1, an integer. So we can not divide the number. We are left at 1. This (1) is called the remainder. We can create a new type of number. We call this number a 'Rational Number'. It is called rational because it is defined by a ratio of two numbers. The expression \\frac{5}{2} is 2.5 in decimal notation, because the remainder is only half (0.5) that of 2.",
    },
    remainder: {
        x: -518.6666666666679,
        y: -12842.833333333332,
        r: 100,
        link: ["21"],
        title: "Remainder",
        facts: "If you divide a number, you subtract the denominator from the numerator until the numerator is zero. Sometimes, the subtraction hops over the zero. In the expression 7 / 3, we first subtract via 7 - 3, which is 4. Then we subtract via 4 - 3, which is 1. Then we subtract via 1 - 3, which is -2. We have hopped over 0. If we want integer division, we use what we call a 'remainder'. We go back and look at the number that was before the jump over 0. This was 1. So we can now say: 7 / 3 is the same as 2, with remainder 1. Why is it 2? Because we could subtract 2 times.",
    },
    integer_mul: {
        x: 1027.3333333333321,
        y: -12373.833333333332,
        r: 100,
        link: [],
        title: "Integer Multiplication",
        facts: "When multiplying two integers (using the * or x symbol), you will always get a new integer. 4 x 3 is 12. Remember, integers can be negative, like -5. The expression -5 x 2 is -10, which is an integer. When you multiply negative number, you can move them 'out' of the multiplication: -5 x 2 can be written as -(5 x 2). You can now calculate 5 x 2, which is 10. You put 10 where 5 x 2 is: -(10). You remove the parentheses, and get -10.",
    },
    integers: {
        x: 521.3333333333321,
        y: -11872.833333333332,
        r: 100,
        link: ["integer_division", "rationals", "integer_mul", "integer_addition"],
        title: "Integers",
        facts: "Remember from 'Natural Numbers' that -1 is not a natural number, because it has a minus sign in the number. When you subtract: $$3 - 4$$ you will not get a natural number. The expression $$3 - 4$$ evaluates to $$-1$$ This is not a natural number. One type of number can create other types of numbers. All natural numbers are also integers, but not all integers are natural numbers.\n<br><br>\nHere is the integer number line.\n\n<img src=\"Textures/integers-numbers-on-number-line.png\">",
    },
    natural_multiplication: {
        x: -766.6666666666679,
        y: -11162.833333333332,
        r: 100,
        link: [],
        title: "Multiplication",
        facts: "Multiplication is an operation on two natural numbers. It always generates a new natural number. It can not create a non-natural number. We use the (*) or (x) symbol for multiplication. The expression 5 x 4 is the same as the number 20. The expression can be read as (5 + 5 + 5 + 5). There are 4 fives, which are added together. This means that 3 x 6 is the same as (3 + 3 + 3 + 3 + 3 + 3). This number is 18.",
    },
    integer_addition: {
        x: 983.3333333333321,
        y: -11893.833333333332,
        r: 100,
        link: ["integer_mul"],
        title: "Integer Addition",
        facts: "Adding integers is very similar to natural numbers. 4 and 5 are both natural numbers as well as integer numbers. Adding them gives 9. This is also a natural number and an integer number. Integers can be negative. This means they have a minus sign in the number. The expression $$5 + -3$$ contains two numbers, '5', and '-3'. When you see a '+ -', you can replace the '+ -' by just '-'. You then get $$5 - 3$$ which is subtraction. You get\n\n$$2$$\n\nWhen you see $$5 + -3$$ think that you have temperature 5, and you're adding 3 ice blocks (because of -, they are cold). The temperature goes down.",
    },
    integral: {
        x: 0,
        y: -18500,
        r: 100,
        link: [],
        title: "Integration",
        facts: "$$\\int$$ is the integration symbol, it means \"to sum\" over an infinitesimally small intervals.",
    },
};
