"use strict";

var all_bubbles = {
    20: {
        x: 937.333333333333,
        y: -5266.833333333333,
        r: 100,
        color: "bubbleHL",
        link: [],
        title: "Editing",
        facts: "Check out the help menu in the top right corner of the screen.\n<br>\nYou can put arbitrary html (images, links, ...) in these boxes. We also support latex using <a href=\"https://www.mathjax.org/\">MathJax</a>.  We use the $$\\$\\$$$ quotes to start a mathjax context. Here is an example:\n<br>\n$$ \\frac{\\partial c}{\\partial t} = e^{-t} $$\nYou can also use inline math using single dollar signs: $\\int$.\nAfter you're done editing, you've only really edited the graph locally. Nobody else who visits this website will see your edits.<br>If you want to publicize your edits, press 'g' (this creates a data file), and send it to the developers, or visit us on <a href=\"https://github.com/BourgondAries/hmm\">github</a> and open up a pull request of leave an issue.\n<br>\n<br>\nContact us at any of these addresses:\n<br>\n<a href=\"mailto:macocio@gmail.com\">macocio@gmail.com</a><br>\n<a href=\"mailto:kevinrs@stud.ntnu.no\">kevinrs@stud.ntnu.no</a>\n",
    },
    21: {
        x: 2014.3726397876217,
        y: -12452.538725734197,
        r: 100,
        color: "bubbleHL",
        link: [],
        title: "Modulo",
        facts: "The operation used to find the remainder is called the modulo operation. The remainder is sometimes called the modulus. <br> \n<br>\n<span style=\"font-weight: bold;\">Notation:</span> <br>\nExample: <br>\n$$1 \\equiv 4 \\mod{3}$$\nGenerally it looks like this: <br>\n$$r \\equiv a \\mod{n}$$\n\na is called the dividend and a the divisor. <br>\n\n<br>\n<span style=\"font-weight: bold;\">Note:</span> \nThere are different definitions for negative dividends, depending on tool for calculation. <br>\n<br>\n<span style=\"font-weight: bold;\">Uses:</span> <br>\nThe modulo operation is sometimes used in programming. The most basic use of this operation is to find whether a number (the dividend) is an odd or even number. Simple use 2 as the divisor and see if the modulus is 1 (odd) or 0 (even). <br>\n<br>\nModulo is also used in cryptography and hashing.",
    },
    22: {
        x: -977.6273602123783,
        y: -13461.205392400865,
        r: 100,
        color: "bubbleHL",
        link: [],
        title: "Exponents",
        facts: "Exponents is a notation for repeated multiplication. <br>\n<span style=\"font-weight: bold;\">Example:</span> <br>\n$$5\\times 5\\times 5\\times 5$$\nIt takes a lot of space, but thanks to exponents we can write the same thing as: <br>\n$$5^4$$\n5 is called the base and 4 the exponent. <br>\nAnother example:\n$$3\\times 3\\times 3$$\nis the same as\n$$3^3$$\nand this is the same as\n$$9$$\n<span style=\"font-weight: bold;\">General notation looks like:</span> <br>\n$$b^a$$\nAgain here b is the base and a the exponent.\nThis means we calculate\n$$b \\times b \\times b \\times ... \\times b$$ 'a' times.",
    },
    23: {
        x: 112.98481831756422,
        y: -15751.270864443333,
        r: 100,
        color: "bubbleHL",
        link: ["26","24"],
        title: "Square root",
        facts: "If you 'take' the square root of a number, you find a new number which if you multiply it with itself, you get the number you started with. <br>\n<span style=\"font-weight: bold;\">Example:</span> <br>\n$$\\sqrt{4} = 2$$\nBecause: <br>\n$$2 \\times 2 = 4$$\n<br>\n<br>\n<strong>Example:</strong>\n<br>\nSometimes you have a polynomial root like\n\n$$ x^2 - 9 = 0 $$\n\n$$ \\Rightarrow x^2 = 9 $$\n\nHow do we solve this?\n<br>\nWe use the square root operation.\nThis operation divides the exponent $2$.\n\nRemember that you can use an operation on both sides and that the equation will remain valid.\n\n$$ \\Rightarrow \\sqrt{x^2} = \\sqrt{9} $$\n\nNow, dividing the first exponent by $2$ is easy:\n\n$$ \\Rightarrow x^1 = \\sqrt{9} $$\n\nWhat about $\\sqrt{9}$? If we look closely, we see that $3^2 = 9$. This means that we can <em>substitute</em> $9$:\n\n$$ \\Rightarrow x^1 = \\sqrt{3^2} $$\n\nAgain, divide the exponent by two\n\n$$ \\Rightarrow x^1 = 3 $$\n\nBecause $x^1 = x$, we get $x = 3$.\nAnd we're done (almost).\n\nDid you notice that $(-3)^2 = 9$ too? In that case, we would get $x = -3$\n\nThis means that there are $2$ answers! $-3$ and $3$ are both equally valid answers. We call this solution a solution of <em>multiple roots</em>.",
    },
    24: {
        x: -498.3485150157694,
        y: -15797.270864443333,
        r: 100,
        color: "bubbleHL",
        link: [],
        title: "nth root",
        facts: "You have learned about the square root, in that case n was 2. But n doesn't have to be 2, it can be any positive integer. <br>\n<br> If we ask ourselves what is the nth root of a number? It is another number which is you multiply is by itself n times you get the number you started with.\n$$\\sqrt[4]{16} = 2$$\nBecause:\n$$2 \\times 2 \\times 2 \\times 2 = 16$$\nor if we use eponentials:\n$$2^4 = 16$$\nGenerally:\n$$r^n = x$$\nr is the nth root of x.",
    },
    25: {
        x: -926.3485150157694,
        y: -15991.270864443333,
        r: 100,
        color: "bubbleHL",
        link: ["24","386721657746765"],
        title: "Decimal power",
        facts: "We know what it means to find the nth root or calculate an exponential with a positive whole number. But can we do the same with a decimal number?<br>\nWhat does the following equal?\n$$ 5^{2.5} $$  \n\nRemember that\n\n$$ 5^2 = 5 \\times 5 $$\n\nHowever, with the added 0.5, we can simply multiply with the square root:\n\n$$ 5^{2.5} = 5^2 \\times 5^{0.5} = 5 \\times 5 \\times \\sqrt{5} $$\nWhat about:\n$$5^{3.375}$$\nThis can similarly be written as:\n$$5^{3.375} = 5^3 \\times 5^{0.375}$$ \nAnd\n$$0.375 = \\frac{3}{8}$$\nSo\n$$5^{0.375} = 5^{\\frac{3}{8}}$$\nRemember\n$$\\sqrt{5} = 5^{0.5} = 5^{\\frac{1}{2}} $$\nWhich is the same as: \n$$\\sqrt[2]{5^1}$$\n(we usually don't write 2 next to the root sign for the square root since it is implied) <br>\nThis must mean that\n$$5^{\\frac{3}{8}} = \\sqrt[8]{5^3}$$\nWhich is the 8th root of\n$$5^3 = 125$$\nSo\n$$5^{3.375} = 125 \\times \\sqrt[8]{125}$$\nThat's cool, but what if the exponent is an irrational number? These can't be written as a rational number. We will now use variables <br>\n$$b^a$$\n\nTo be continued..",
    },
    26: {
        x: -491.1336485814036,
        y: -16109.057325369176,
        r: 100,
        color: "bubbleHL",
        link: ["29","27","58","25","7310707662813565"],
        title: "Irrationals",
        facts: "Irrational numbers are numbers that can not be represented by a fraction like\n\n$$ \\frac{103}{7} $$\n\nAn example of an irrational number is\n\n$$ \\sqrt{2} \\approx 1.414 $$\n\nWe use the symbol\n\n$$ \\mathbb{I} $$\nto mean \"all irrational numbers\".\n\n<br>\n<br>\n<span style=\"font-weight: bold;\">Proof:</span>\nLet's suppose $$\\sqrt{2}$$ is a rational number. Then we can write it $$\\sqrt{2}  = \\frac{a}{b}$$ where a, b are whole numbers, b not zero.\n<br><br>\nWe additionally assume that this a/b is simplified to lowest terms, since that can obviously be done with any fraction. Notice that in order for a/b to be in simplest terms, both of a and b cannot be even. One or both must be odd. Otherwise, we could simplify a/b further.\n<br><br>\nFrom the equality $$\\sqrt{2} = \\frac{a}{b}$$ it follows that $$2 = \\frac{a^2}{b^2}$$  or  $$a^2 = 2 \\cdot b^2$$.  So the square of a is an even number since it is two times something.\n\nFrom this we know that a itself is also an even number. Why? Because it can't be odd; if a itself was odd, then a · a would be odd too. Odd number times odd number is always odd.\n\nIf a itself is an even number, then a is 2 times some other whole number. In symbols, a = 2k where k is this other number. We don't need to know what k is; it won't matter. Soon comes the contradiction.\n\nIf we substitute a = 2k into the original equation $$2 = \\frac{a^2}{b^2}$$, this is what we get:\n\n$$2    =    (2k)^2/b^2$$\n$$2    =    4k^2/b^2$$\n$$2\\cdot b^2    =    4k^2$$\n$$b^2    =    2k^2$$\nThis means that $b^2$ is even, from which follows again that b itself is even. And that is a contradiction.",
    },
    27: {
        x: -261.1336485814036,
        y: -16513.057325369176,
        r: 100,
        color: "bubbleHL",
        link: ["31"],
        title: "Real",
        facts: "Real numbers contain both rational and irrational numbers. An irrational number is never rational, and a rational number is never irrational. A real number can be either rational or irrational.\n<br><br>\nWe use the symbol\n$$ \\mathbb{R} $$\nwhich means \"all real numbers\".",
    },
    28: {
        x: 306.37263978762167,
        y: -14621.205392400865,
        r: 100,
        color: "bubbleHL",
        link: ["32","30","34"],
        title: "Polynomials",
        facts: "Polynomials are expressions. Here is an example of a polynomial:\n\n$$ x^2 + 4\\cdot x - 2 $$\n\nYou can put a number into x, and the polynomial will become another number.\n<br><br>\nIf x is 2:\n\n$$ 2^2 + 4\\cdot 2 - 2 $$\n\nWhich becomes\n\n$$ 4 + 8 - 2 $$\n$$ \\Rightarrow 10 $$\n\nPolynomials can have any natural number exponent:\n\n$$ 54\\cdot x^{143} + \\frac{73}{3}\\cdot x^3 + 94 $$\nis a valid polynomial. <br>\n<br>\n<Strong>Properties:</strong><br>\nThe x's must be raised to a non-negative integer exponent and the polynomial can't contain any special functions like logarithmic or trigonometric functions. ",
    },
    29: {
        x: -850.9910237265713,
        y: -16635.310585697684,
        r: 100,
        color: "bubbleHL",
        link: ["27","31","41"],
        title: "Transcendentals",
        facts: "Transcendental numbers are numbers that can not be the root of a polynomial.\n<br><br>\nYou can not find any polynomial that has a root that is a transcendental number.\n\n<span style=\"font-weight: bold;\">Example:</span>\n<br>\nThis number is called 'pi', pronounced \"pie\". It is very important. You will use it later. You will use it a lot.\n$$ \\pi \\approx \\frac{355}{113} \\approx 3.141593 $$\nAnother number that is transcendental and extremely important is Euler's Number:\n$$ e \\approx 2.71828 $$",
    },
    30: {
        x: 945.6666666666661,
        y: -15333.166666666664,
        r: 100,
        color: "bubbleHL",
        link: ["34"],
        title: "Polynomial Root",
        facts: "The root of a polynomial denotes the following:\n\nRemember: A polynomial is an <span style=\"font-weight: bold;\">expression</span> like\n$$ x^2 + 4\\cdot x - 2.25 $$\n\nWhen you say \"The root of a polynomial\", you mean \"the x value that will turn the expression into 0\":\n\n$$ x^2 + 4\\cdot x - 2.25 = 0 $$\n\nWhat is the x value to make the equation true?\n<br>\n<br>\nLet's try x = 0.5:\n$$ 0.5^2 + 4\\cdot 0.5 - 2.25 = 0 $$\n$$ \\Rightarrow 0.25 + 2 - 2.25 = 0 $$\n$$ \\Rightarrow 2.25 - 2.25 = 0 $$\n$$ \\Rightarrow 0 = 0 $$\n\nWe see that 0.5 works as a root! 0.5 is the root of this polynomial.",
    },
    31: {
        x: -385.1336485814036,
        y: -16873.057325369176,
        r: 100,
        color: "bubbleHL",
        link: ["7982720977690619"],
        title: "Complex",
        facts: "Complex numbers are not complicated or 'complex' in difficulty. They are easy.\n\nSuppose you have a polynomial\n$$ x^2 + 1 $$\n\nWhat is the root of this polynomial?\n\n$$ x^2 + 1 = 0 $$\n$$ \\Rightarrow x^2 = -1 $$\n$$ x = \\sqrt{-1} $$\n\nThe square root of a negative number makes no sense. To make sense of it, we use complex numbers. We claim that:\n\n$$ \\sqrt{-1} = i $$\n\n'i' is the complex unit, as '1' is the unit in other numbers.\n<br>\nThe root of the polynomial is:\n\n$$ 0 + i $$\n\nComplex numbers have a 'real' and 'complex' part.\n<br><br>\nWe use the symbol\n\n$$ \\mathbb{C} $$\n\nto mean \"all complex numbers\".",
    },
    32: {
        x: 651.6666666666661,
        y: -15179.166666666664,
        r: 100,
        color: "bubbleHL",
        link: ["34"],
        title: "Degree",
        facts: "The degree of the polynomial is the number that is the largest exponent.\n\n$$ x^4 + x^3 - 3 $$\n\nis a polynomial of degree 4.\n\n$$ x^8 + x^{93} - 94 $$\n\nis a polynomial of degree 93. 94 is not an exponent.",
    },
    33: {
        x: 927.5330180852634,
        y: -14681.057325369176,
        r: 100,
        color: "bubbleHL",
        link: ["55","54","30","42"],
        title: "Equations",
        facts: "An equation is an assertion of fact. We use the $=$ symbol for equations.\n\n$$ 1+2 = 3 $$\n\nThe above is a fact. It is always true, even if both sides look different.\n<br>\nYou can write\n\n$$ x + 3 = 0 $$\n\nWhat does x need to be for the equation to be true?\n\n$$ x = -3 $$\n\nBecause\n\n$$ (-3) + 3 = 0 $$\n\n\n<br>\n<br>\n<strong>Trivia:</strong>\n<br>\nDid you know that equations can be <em>solved</em> without testing all possibilities of $x$?",
    },
    34: {
        x: 435.7059731209547,
        y: -15569.87205906753,
        r: 100,
        color: "bubbleHL",
        link: ["23"],
        title: "1. Polynomial",
        facts: "Sometimes when we have a polynomial, the order of that polynomial is first This is called a first order polynomial or a linear polynomial.\n<br>\nThis is a first order polynomial:\n$$ x + 3 $$\nThis is <strong>not</strong> a first order polynomial:\n$$x^3 + x - 5$$\nBecause in that polynomial $x$ is raised to the power of $3$. There must be a x raised to the power of 1 and there can't be one raised to any number above 1. <br>\n<br>\nIt is called a linear polynomial because if you increase $x$ by any amount, the value of the polynomial will increase the same amount.\n<br>\nTo find the root, we add ' = 0', we get:\n\n$$ x + 3 = 0 $$\n\nFirst order polynomials can easily be solved for 'x'. You first add or subtract to remove the term:\n\n$$ x + 3 - 3 = -3 $$\n\nYou subtract 3 from both sides\n\n$$ x + (3 - 3) = -3 $$\n$$ \\Rightarrow x + (0) = -3 $$\n$$ \\Rightarrow x = -3 $$\n\nWe have now solved the root of the polynomial. It is $-3$.\n<br>\nIf you have a polynomial with a multiplier:\n\n$$ 43\\cdot x + 3 = 0 $$\n\nFirst, you remove the <span style=\"font-weight: bold;\">term</span>: (3) is the term.\n\n$$ 43\\cdot x + 3 - 3 = -3 $$\n$$ \\Rightarrow 43\\cdot x + (3-3) = -3$$\n$$ \\Rightarrow 43\\cdot x + (0) = -3$$\n$$\\Rightarrow 43\\cdot x = -3$$\n\nNow you can divide both sides by 43:\n\n$$\\Rightarrow \\frac{43}{43}x = \\frac{-3}{43} $$\n$$\\Rightarrow x = \\frac{-3}{43}$$\n\nWe have now solved the root.",
    },
    35: {
        x: 542.3181516508976,
        y: -15896.604197776667,
        r: 100,
        color: "bubbleHL",
        link: ["23","58"],
        title: "2. Polynomial",
        facts: "The second order polynomial is more difficult to find the root for. Here is an example of a second order polynomial:\n\n$$ 3x^2 + 5x + 2 $$\n\nTo find the root, we add '= 0':\n\n$$ 3x^2 + 5x + 2 = 0 $$\n\nWe have to <span style=\"font-weight: bold;\">remember</span> the equation\n\n$$ x = \\frac{-b \\pm \\sqrt{b^2-4ac}}{2a} $$\n\nThis says: \"The root (x) is the right side of the = sign\".\n\nWhat do a, b, and c mean? The root equation is assumed to be of the form:\n\n$$ a\\cdot x^2 + b\\cdot x + c = 0 $$\n\nWe see that:\n\n$$ a = 3, b = 5, c = 2 $$\n\nWe can put these number into the equation and get:\n\n$$ x_1 = \\frac{-5+\\sqrt(1)}{6}$$\n$$ \\Rightarrow x_1 = \\frac{-4}{6} = \\frac{-2}{3}$$\n$$ x_2 = \\frac{-5-\\sqrt(1)}{6}$$\n$$ \\Rightarrow x_2 = \\frac{-6}{6} = -1$$\n\nNote the\n\n$$\\pm$$\n\nThis means that there will be two roots! In fact, an polynomial of second order has two roots!\n<br>\nHow many roots do you think a polynomial of third order has?",
    },
    36: {
        x: 989.7327857972377,
        y: -16824.205823792923,
        r: 100,
        color: "bubbleHL",
        link: ["37"],
        title: "Right Triangle",
        facts: "A right triangle is any triangle with a corner that is exactly $$90^\\circ$$\n\n<img src=\"Textures/small-right-triangle.png\">\n<br>\nWe use a square to point out where that corner is.\n<br>\n<img src=\"Textures/small-right-triangle-noted.png\">\n<br>\nHere, a, b, and c mean the <span style=\"font-weight: bold;\">lengths</span> of the sides.\n<br>\nA, B, and C mean the <span style=\"font-weight: bold;\">angles</span> of the corners.\n<br>\n\nWe see that C is 90 degrees.\n\nWe call the side opposite to the $90^\\circ$ corner the <strong>hypotenuse</strong>.\n\n<br>\n<br>\n<strong>Trivia:</strong>\nDid you know that all triangles can be <em>decomposed</em> into right triangles?",
    },
    37: {
        x: 1222.8663514185964,
        y: -17209.057325369176,
        r: 100,
        color: "bubbleHL",
        link: ["2752534480731885"],
        title: "Pythagorean Theorem",
        facts: "The Pythagorean theorem is an ancient triangle theorem.\nA theorem is to be considered an \"eternal truth\". It can never be broken. It is impossible.\n\n<img src=\"Textures/small-right-triangle-noted.png\">\n\n<br>\n<span style=\"font-weight: bold;\">Theorem:</span>\n$$ c^2 = a^2 + b^2 $$\n<strong>End of Theorem</strong>\n<br>\nThis can be rewritten as \n\n$$ c = \\sqrt{a^2 + b^2} $$\n\nThis means that having two of the a, b, c numbers, you can calculate the other one. This is <span style=\"font-weight: bold;\">only for right triangles</span> (with a $90^\\circ$ corner).",
    },
    38: {
        x: -950.3485150157694,
        y: -15589.270864443333,
        r: 100,
        color: "bubbleHL",
        link: ["24","25"],
        title: "Power-Add rule",
        facts: "Multiplying the same bases 'b' of different powers allows us to simply add the powers.\n\nRemember that a base of power 'p' is given as:\n\n$$ b^p $$\n\nIf we multiply two numbers of base 5, both with different powers:\n\n$$ 5^4 \\times 5^6 $$\n\nThis number is simply\n\n$$ 5^{4 + 6} = 5^{10} $$",
    },
    39: {
        x: -1302.9910237265713,
        y: -16535.310585697684,
        r: 100,
        color: "bubbleHL",
        link: ["41"],
        title: "Logarithms",
        facts: "The logarithm is the inverse operation to exponentiation. If you find the logarithm to a number for a given base you find the exponent which you have to raise the base with to make the number you started with. <br>\n<br>\nLet's look at some examples, we will start with base 10: <br>\n<br>\n$$\\log_{10}(100)$$\nIf we evaluate this expression we will find out which power we have to raise 10 to in order to get 100. <br>\nWe know:\n$$10^2 = 100$$\nTherefore\n$$\\log_{10}(100) = 2$$\nLet's look at another example:\n$$\\log_{2}(64)$$\nIn words, what number, when used as exponent with base 2 equals 64?<br>\nAnswer:\n$$2^6 = 64$$\n$$\\log_{2}(64) = 6$$\nLet's look at some identities:\n$$\\log_{b}(b^p) = p$$\n$$\\log_{b}(x^p) = p \\log_{b}(x)$$\nFrom the first we can see that:\n$$\\log_{b}(b) = 1$$\nSome more identities:\n$$b^{log_{b}(x)} = x$$\n$$log_{b}(xy) = log_{b}(x) + log_{b}(y)$$\n$$log_{b}(\\frac{x}{y}) = log_{b}(x) - log_{b}(y)$$",
    },
    40: {
        x: -645.6576903932379,
        y: -17067.31058569768,
        r: 100,
        color: "bubbleHL",
        link: ["31"],
        title: "Natural logarithm",
        facts: "The natural logarithm is the logarithm with base:\n$$e$$\n\nWe normally write:\n$$\\log_{e}(x)$$\nSince $e$ is the base. This base is so often used that it is referred to as\n$$\\ln(x)$$\n\nwhere x is any number.",
    },
    41: {
        x: -1100.3243570599045,
        y: -16948.643919031012,
        r: 100,
        color: "bubbleHL",
        link: ["40"],
        title: "Euler's number",
        facts: "$$e = \\mathop {\\lim }\\limits_{n \\to \\infty } \\left( {1 + \\frac{1}{n}} \\right)^n$$\n\n\nThis is an important number in mathematics, for one it is the base number for the natural logarithm. <br> \nThis first six digits of the number are:\n$$e \\approx 2.71828$$\nEuler's number is irrational, it is not a ratio of integers, and has an infinite amount of digits.",
    },
    42: {
        x: 1047.7327857972377,
        y: -15810.205823792923,
        r: 100,
        color: "bubbleHL",
        link: ["4976277242509039","999093708594227","43","93946261109823"],
        title: "Functions",
        facts: "A function takes a number, and turns it into another number. We write a function like an equation:\n\n$$ f(x) = x + 3 $$\n\n<strong> f </strong> is just a name we choose. It can be anything.\n<br>\nWhat is $f(1)$? $f(1)$ means $f(x = 1)$, which means that $x$ becomes $1$. The expression then becomes $1 + 3$, which is $4$. So:\n\n$$ f(1) = 4 $$\n\n<strong>Can a function to more?</strong>\n<br>\nA function can do anything to the number. Here is another function:\n\n$$ g(x) = 7\\cdot x + 15 - 3 \\cdot x^2 $$\n\n<strong> g </strong> is just a name we choose. It can be anything.\n<br>\n\nDoes $g(x)$ look familiar? It's a second order polynomial!",
    },
    43: {
        x: 190.947486311597,
        y: -16608.58130081301,
        r: 100,
        color: "bubbleHL",
        link: ["3559675231308331","5862308996258507","4419110068750971","5576399967555123","integral"],
        title: "Derivative",
        facts: "The derivative of a function is the instantaneous rate of change of that function. We often use ' to denote a derivative of a function of a single variable: $ f' $ is the derivative of $f$.\n\nDerivatives can be defined in the following manner\n\n<br>\n<br>\nlet $f$ be a function of $x$: $f(x)$:\n$$ f'(x) = \\lim_{h \\rightarrow 0}\\frac{f(x+h) - f(x)}{h} $$\n\nDon't worry if you don't understand this. After having done some derivations you'll see how intuitive the concept is.",
    },
    44: {
        x: -89.14393562303121,
        y: -17835.96656711465,
        r: 100,
        color: "bubbleHL",
        link: [],
        title: "FToC",
        facts: "<strong>FToC</strong> stands for the <strong>Fundamental Theorem of Calculus</strong>.\n<br>\n<br>\n<strong>Theorem:</strong>\n<br>\nLet $ F'(t) = f(t) $, then\n$$\\int^b_a f(t)\\space dt = F(b) - F(a) $$\n<strong>End of Theorem</strong>\n\nThis theorem binds derivation and integration together into <strong>calculus</strong>.",
    },
    45: {
        x: 232.37263978762167,
        y: -13501.205392400865,
        r: 100,
        color: "bubbleHL",
        link: ["53"],
        title: "Expressions",
        facts: "A mathematical expression is any combination of operators and numbers. The expression <em>collapses</em> into a new number.\n<br>\nThe following is an expression\n$$ 4 + \\frac{5}{3} + 2 \\cdot 8 $$\nThis expression collapses into $\\frac{65}{3}$.\n\nNote that $\\frac{65}{3}$ is also an expression. The number is $21.\\bar{6}$. A single number is also an expression. A single number is not <em>collapsable</em>. It is the most collapsed expression.\n<br>\nThe bar above $6$ means that the number never ends: $21.66666666...$.\n<br>\n<strong>Precedence & Associativity:</strong>\n<br>\nWhen evaluating (collapsing) an expression, you must use certain rules.\n<br>\n<ol class=\"horizontal-center\">\n  <li>Exponents first</li>\n  <li>Multiplication and Division second</li>\n  <li>Addition and Subtraction last</li>\n</ol>\n<br>\nWhat if you have $ 5/3/2 $? Then we use <strong>associativity</strong>. Associativity means which way we travel. Associativity for multiplication, division, addition, and subtraction is <em>left</em>. This means that\n\n$$ 5/3/2 = ((5/3)/2) $$\n\nFor exponentiation, the associativity is <em>right</em>:\n\n$$ 5\\hat{} 3\\hat{} 2 = (5\\hat{}(3\\hat{} 2)) $$\n\nNow you know that the following expression collapses like so:\n\n$$ 5\\cdot 3 / 5 / 2 / 8 \\cdot 3 / 6 = ((((((5\\cdot 3) / 5) / 2) / 8) \\cdot 3) / 6) $$\n\n<br>\n<strong>Trivia:</strong>\n<br>\nDid you know that many people never learn about operator associativity?",
    },
    46: {
        x: 534.3775510204096,
        y: -10815.418367346938,
        r: 100,
        color: "bubbleHL",
        link: ["47","integers"],
        title: "Natural Subtraction",
        facts: "Subtracting natural numbers is done by starting on the number line, and moving to the left.",
    },
    47: {
        x: 1005.3775510204096,
        y: -11145.418367346938,
        r: 100,
        color: "bubbleHL",
        link: [],
        title: "Natural Division",
        facts: "Division of natural numbers",
    },
    48: {
        x: 663.5330180852634,
        y: -14217.057325369176,
        r: 100,
        color: "bubbleHL",
        link: ["1990676233998147"],
        title: "Symbolic Subtraction",
        facts: "Subtracting symbols is similar to adding\n\n$$ -x - x $$\n\ncollapses into \n\n$$ -2\\cdot x$$\n\nYou can read it as\n\n$$ -x + -x $$",
    },
    49: {
        x: -300.52040816326553,
        y: -12952.765306122446,
        r: 100,
        color: "bubbleHL",
        link: ["50"],
        title: "Rational Addition",
        facts: "Adding rational numbers is different from integers and natural numbers.\n<br>\n<strong>Example:</strong>\n<br>\n$$ \\frac{3}{4} + \\frac{2}{4} $$\n\nThis is the same as\n\n$$ \\frac{3 + 2}{4} $$\n\nWhich is the same as\n\n$$ \\frac{5}{4} $$\n\n<strong>Rule:</strong>\n<br>\nWhen the denominator is the same, you can simply add the numerators together.\n<br>\nWhat if the denominators are not the same? Come back after learning: \n<a onclick=\"teleportTo(50);\">Rational multiplication</a>\n<br>\n<strong>Example:</strong>\n$$ \\frac{3}{4} + \\frac{2}{5} $$\nWhat number is this?\n<br>\nThe technique is to multiply by the opposite denominator:\n\n$$ \\frac{5}{5}\\cdot \\frac{3}{4} + \\frac{4}{4}\\cdot \\frac{2}{5} $$\n\nYou can multiply because the values $\\frac{5}{5}$ and $\\frac{4}{4}$ are 1, which means the number (the result) does not change.\n<br>\nRemember that multiplying rationals allows you to multiply the numerators together independently from the denominators:\n\n$$ \\frac{5\\cdot 3}{20} + \\frac{4\\cdot 2}{20} $$\n\nThe denominators are now the same. You can collapse this expression into\n\n$$ \\frac{5\\cdot 3 + 4 \\cdot 2}{20} $$\n\nWhich can collapse into\n\n$$ \\frac{15 + 8}{20} $$\n\n$$ \\frac{23}{20} $$",
    },
    50: {
        x: -636.5204081632655,
        y: -13240.765306122446,
        r: 100,
        color: "bubbleHL",
        link: ["22"],
        title: "Rational Multiplication",
        facts: "Rational multiplication has a easy rule to remember. <br>\n<strong>Example:</strong>\n$$\\frac{1}{2} \\cdot \\frac{1}{4}$$\nThis is the same as:\n$$\\frac{1}{8}$$\nAs you can see we multiplies the denominators<br>\nBut also the numerator, check out this example:\n$$\\frac{3}{8} \\cdot \\frac{4}{5}$$\nThis equals\n$$\\frac{3 \\cdot 4}{8 \\cdot 5}$$\nWhich again is the same as\n$$\\frac{12}{40}$$",
    },
    51: {
        x: 607.4795918367345,
        y: -13004.765306122446,
        r: 100,
        color: "bubbleHL",
        link: ["52"],
        title: "Rational Subtraction",
        facts: "Like with rational addition must must make sure the denominators are the same in order to subtract the rational numbers.\n$$\\frac{5}{3} - \\frac{2}{3}$$\nThese have the same denominator, so all we need to do is subtract the numarators.\n$$\\frac{5-2}{3}$$\nWhich is the same as\n$$\\frac{3}{3}$$\nIf the denominators aren't equal we must make them equal in order to continue.",
    },
    52: {
        x: 1035.4795918367345,
        y: -13050.765306122446,
        r: 100,
        color: "bubbleHL",
        link: ["62"],
        title: "Rational Division",
        facts: "Let's look at an example\n$$\\frac{1}{4} / \\frac{2}{3}$$\nThe rule goes as follows: Flip the number on the right. That is, put the number on the top on the bottom and vice versa, and then multiply the numbers.<br>\n<br>\nSo we get (notice the last fraction is flipped)\n$$\\frac{1}{4} \\cdot \\frac{3}{2}$$\nWhich is\n$$\\frac{1 \\cdot 3}{4 \\cdot 2}$$\nFinally\n$$\\frac{3}{8}$$\nAnother way to do it is start with:\n$$\\frac{\\frac{1}{4}}{\\frac{2}{3}}$$\nThen multiply with $\\frac{3}{3}$ and after that $\\frac{4}{4}$. Notice that $2$ and $3$ are the denominators and that  $\\frac{3}{3}$ and $\\frac{4}{4}$ equals $1$. <br>\n<br>\nLet's do the multiplications:\n$$\\frac{\\frac{1}{4}}{\\frac{2}{3}} \\cdot \\frac{3}{3}$$\nRewritten as \n$$\\frac{\\frac{1}{4} \\cdot 3}{\\frac{2}{3} \\cdot 3}$$\nOr\n$$\\frac{\\frac{1}{4} \\cdot \\frac{3}{1}}{\\frac{2}{3} \\cdot \\frac{3}{1}}$$\nWe get:\n$$\\frac{\\frac{3}{4}}{2}$$\nNow multiply with $\\frac{4}{4}$\n$$\\frac{\\frac{3}{4}}{2} \\cdot \\frac{4}{4}$$\nRewritten\n$$\\frac{\\frac{3}{4} \\cdot \\frac{4}{1}}{2 \\cdot \\frac{4}{1}}$$\nFinally\n$$\\frac{3}{8}$$",
    },
    53: {
        x: 256.37263978762167,
        y: -14097.205392400865,
        r: 100,
        color: "bubbleHL",
        link: ["28","33","48"],
        title: "Symbolic Expressions",
        facts: "A symbolic expression is an expression where we use one or more <strong>symbols</strong>. A symbol is the name of a <strong>variable</strong>. A variable is simply a number that we don't want to write down yet, e.g. because we don't know what it's value is.\n<br>\n<strong>Example:</strong>\n$$ x + 3 $$\n\nWe can later choose to set $x$ to any number we like. Think of a variable, or $x$, like a box. We can put any number in the box. When there is a number inside the box, we can collapse the expression.\n<br>\nLet's put $8$ inside $x$. The expression becomes $8+3$. This collapses into $11$.",
    },
    54: {
        x: 1503.0089762734278,
        y: -14981.310585697684,
        r: 100,
        color: "bubbleHL",
        link: ["55","56","57"],
        title: "Equal sign",
        facts: "The equal sign looks like this:\n$$=$$\nThe sign indicates equality, usually between two expressions. You can also combine multiple equal sign and expressions like this:\n$$1 + 2 = 6 - 3 = 9 / 3$$\n\nThese need to be read as:\n\n$$ 1 + 2 = 6 - 3 $$\n\nand \n\n$$ 6 - 3 = 9 / 3 $$\n\n<br>\n<br>\n<strong>Trivia:</strong>\n<br>\nDid you know that $=$ is one of the most powerful tools of mathematics?",
    },
    55: {
        x: 1577.0089762734278,
        y: -14625.310585697684,
        r: 100,
        color: "bubbleHL",
        link: ["2727107890740015"],
        title: "Implies sign",
        facts: "This is the implies sign: \n$$\\Rightarrow$$\nand is not to be confused with the equal sign. It's a normal mistake to do. Let's learn the difference! <br>\n<br>\nSimply put, the equal sign is used between two expressions while the implies sign is used between two equations. <br>\n<br>\nLet's look at some examples: <br>\n<br>\nAn expression:<br>\n$$5 + 3 = 8$$\nAn other:<br>\n$$5 = 8 - 3$$\nNote that the second equation is the same is the first only we subtracted 3 from each side. <Strong> Important: </strong> If we do the same operation on both sides of an equation, we can place the implies sign between the old and the new equation, like this:\n$$5 + 3 = 8 \\Rightarrow 5 = 8 - 3$$\nAnother example with symbolic equations:\n$$x + 5 = 2x - 8$$\nWe subtract with x on both sides:\n$$x + 5 = 3x - 8 \\Rightarrow 5 = 2x - 8 $$\nAdd 8 to both sides:\n$$5 = 2x - 8 \\Rightarrow 13 = 2x $$\nDivide by 2 on both sides:\n$$13 = 2x \\Rightarrow 13/2 = x $$\nFinal equation:\n$$x = 7.5$$",
    },
    56: {
        x: 1765.5330180852634,
        y: -15407.057325369176,
        r: 60,
        color: "bubbleHL",
        link: [],
        title: "Not equal",
        facts: "The following sign means not equal:\n$$\\neq$$\nBy using this sign we can express that two number or expressions are not the same.\n$$1 \\neq 2$$\n$$ x \\neq x + 1$$\n\nThis works just like the equal sign, except that it asserts \"the two expressions are not equal\".",
    },
    57: {
        x: 1393.5330180852634,
        y: -15443.057325369176,
        r: 60,
        color: "bubbleHL",
        link: [],
        title: "Approximately equal",
        facts: "The approximately sign is often used when a number has to many digits after the decimal sign.\n$$10/9 \\approx 1.11$$\n$$\\pi \\approx 3.14$$\nThis means that the difference between the two numbers is <em>relatively</em> little.\n\n<br>\n<br>\n<strong>Trivia:</strong>\n<br>\nDid you know that approximations can actually lead to exact mathematics?",
    },
    58: {
        x: 1044.947486311597,
        y: -16422.58130081301,
        r: 120,
        color: "bubbleHL",
        link: ["36","4996274113563965"],
        title: "Trigonometry",
        facts: "In trigonometry we study the relations involving lengths and angles of triangles. <br>\nThis is an arbitrary triangle with all lengths and angles denoted by symbols.\n<br>\n\n<img src=\"Textures/Triangle_with_notations.png\">\n<br>\n\n<br>\n<br>\n<strong>Trivia:</strong>\n<br>\nDid you know that triangles are of the simplest 2D shapes?",
    },
    59: {
        x: 1548.1654388584639,
        y: -17332.072490459585,
        r: 100,
        color: "bubbleHL",
        link: [],
        title: "Law of Sines",
        facts: "The law of sines works for any triangle.\n<br>\n<strong>Theorem:</strong>\n$$ \\frac{\\sin(\\alpha)}{a} = \\frac{\\sin(\\beta)}{b} = \\frac{\\sin(\\gamma)}{c} $$\n<strong>End of Theorem</strong>\n\n<br>\n<img src=\"Textures/Triangle_with_notations.png\">\n<br>",
    },
    60: {
        x: 9456.128422100548,
        y: 8948.56719761075,
        r: 100,
        color: "bubbleHL",
        link: [],
        title: "Magic Carpet",
        facts: "Welcome to the magic carpet, your teleport and taxi. Mathematicians get a 100% discount!\n\n$$ 3000, -30000 $$\n\n<input id=\"carpet\" type=\"text\" placeholder=\"place your order\">\n<button id=\"carpbut\" style=\"width: 100%; height: 5vh;\" onclick=\"eval('teleportTo(' + document.getElementById('carpet').value + ')');\">Woosh!</button>\n<br><br>\nYou can also write the identifier of the node you wish to travel to!\n\n$$ 53 $$\n\nTravels to node ID 53.\n",
    },
    61: {
        x: -81.98639455782313,
        y: -14209.897959183672,
        r: 100,
        color: "bubbleHL",
        link: ["53","4118398304023309"],
        title: "Symbolic Addition",
        facts: "Adding symbols is like adding numbers.\n\n$$ x + x $$\n\nbecomes\n\n$$ 2\\cdot x $$\n\nOr if we use more symbols\n\n$$ x + x + x + x $$\n\ncollapses into\n\n$$ 4\\cdot x $$\n\nIn fact, you can use any number:\n\n$$ 34\\cdot x + x $$\n\ncollapses to\n\n$$ 35\\cdot x $$",
    },
    62: {
        x: 1470.0136054421764,
        y: -13161.897959183672,
        r: 100,
        color: "bubbleHL",
        link: [],
        title: "Percentage",
        facts: "Percentage $\\%$ means 'divide by 100'.\nWhen you see $\\%$ in an expression, you can always replace it by '$/100$'.\n\n$$ 83\\% $$\n\nis the same as\n\n$$ 83/100 $$\n\nor\n\n$$ \\frac{83}{100} $$",
    },
    start: {
        x: 0,
        y: 0,
        r: 100,
        color: "bubbleHL",
        link: ["music"],
        title: "Click here!",
        facts: "Welcome to 'Hmm', the sanctuary of mathematics! To get started, you can drag yourself anywhere using the mouse. The arrow keys, 'wasd', or 'hjkl' can also be used.",
    },
    music: {
        x: 43.86635141859642,
        y: -920.3906587025067,
        r: 100,
        color: "bubbleHL",
        link: ["fullscreen"],
        title: "Music",
        facts: "To change the mute state of music and sounds, press 'm'. You can also click the top-left music button.",
    },
    fullscreen: {
        x: -52.13364858140358,
        y: -1720.3906587025067,
        r: 100,
        color: "bubbleHL",
        link: ["zoom"],
        title: "Fullscreen",
        facts: "'Hmm' is best enjoyed in full screen. Most browsers support this. Press F11 to enter or exit fullscreen mode.",
    },
    zoom: {
        x: 155.86635141859642,
        y: -2592.3906587025067,
        r: 100,
        color: "bubbleHL",
        link: ["7817708969890363"],
        title: "Zoom",
        facts: "You can use the +/- buttons or the scroll wheel to zoom in our out.",
    },
    mouseless: {
        x: 123.86635141859642,
        y: -4152.390658702507,
        r: 100,
        color: "bubbleHL",
        link: ["goal"],
        title: "Mouseless",
        facts: "You can select a node if it's centered, press the space bar to open it. Use movement or escape to close the window.",
    },
    goal: {
        x: 0,
        y: -5000,
        r: 100,
        color: "bubbleHL",
        link: ["devmode","numbers","20"],
        title: "Goal",
        facts: "Your goal is to dive deep into the beauty of mathematics, or not. It's up to you, and you alone.",
    },
    devmode: {
        x: 1500,
        y: -5000,
        r: 100,
        color: "bubbleHL",
        link: [],
        title: "Dev-mode",
        facts: "A little more information is available by pressing 'e'. This opens up 'Developer mode'. It just shows you your current position and the mouse position relative to the screen, in addition to the mouse position in the world.",
    },
    numbers: {
        x: 0,
        y: -10000,
        r: 100,
        color: "bubbleHL",
        link: ["natural_numbers","number_system"],
        title: "Numbers",
        facts: "Numbers are mathematical objects. A number can represent a quantity, they can be used as labels, ordering of objects, or measuring. There are many types of numbers. $1$ is a number. $9.8$ is also a number. Not all numbers can be written only with the use of $0, 1, 2, 3, 4, 5, 6 ,7, 8, 9$. You will learn about these numbers later. <br>\n<br>\n<strong>Trivia:</strong>\n<br>\nDid you know that numbers were invented thousands of years ago, but  the number 0 was invented relatively recently?",
    },
    number_system: {
        x: 656.3775510204096,
        y: -10099.418367346938,
        r: 100,
        color: "bubbleHL",
        link: [],
        title: "Number System",
        facts: "The decimal number system is made up of ten symbols: $0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0$. There are other number systems, which we will not use. The least significant digit is the rightmost digit. This means that 10 is greater than 1. When we compare, we can pad digits so they become the same length. 10 and 1 can be seen as $10$ and $01$. A zero to the left does not change the number. A zero to the right does change the number.\n<br>\n<br>\n<strong>Trivia:</strong>\n<br>\nThe modern decimal number system is called the <em>Hindu-Arabic numeral system</em>.",
    },
    natural_numbers: {
        x: 161.33333333333212,
        y: -10818.833333333332,
        r: 100,
        color: "bubbleHL",
        link: ["natural_numbers_addition","integers","46"],
        title: "Natural Numbers",
        facts: "Natural numbers are whole numbers. They do not have a '.' in the number. $$10$$ is natural number. $$8932$$ is a natural number. $$-3$$ is <em>not</em> a natural number, because it has a minus sign (-). $$5.5$$ is <em>not</em> a natural number because it contains a dot '.'.\n<br>\n<br>\nThis picture shows the natural number line. It never ends to the right.\n<img src=\"Textures/number-line-positive.gif\">\n<br>\nWe use the symbol $ \\mathbb{N} $ to mean \"all natural numbers\".\n<br>\n<br>\n<strong>Trivia:</strong>\n<br>\nDid you know that some mathematicians don't consider $0$ part of the natural numbers?",
    },
    natural_numbers_addition: {
        x: -334.6666666666679,
        y: -10770.833333333332,
        r: 100,
        color: "bubbleHL",
        link: ["natural_multiplication"],
        title: "Natural Addition",
        facts: "You can add natural numbers together. This creates a new number. The symbol for adding is $+$ (called plus). You put two natural numbers on either side of the plus: $3 + 4$. The expression $3 + 4$ is the same as the number $7$.\n\n$$ 3 + 4 $$\n\nWhen adding a number, start on the number line at $0$, and count upwards from left to right.\n<br>\n<br>\n<strong>Trivia:</strong>\n<br>\nDid you know that natural addition never gives you a non-natural number?",
    },
    natural_numbers_subtraction: {
        x: 735.3775510204096,
        y: -11921.418367346938,
        r: 100,
        color: "bubbleHL",
        link: ["integers","integer_division"],
        title: "Integer Subtraction",
        facts: "You can subtract natural numbers. This creates a new number. The symbol for subtracting is '-' (called minus). You put two natural numbers on either side of the minus: $$4 - 3$$ The expression $$4 - 3$$ is the same as the number $$1$$ The expression $$10 - 2$$ is the same as the number $$8$$\nNote that which side of the minus sign you place the number on matters.\n$$4-3$$\nis not the same as\n$$3-4$$",
    },
    integer_division: {
        x: 1228.3775510204096,
        y: -12147.418367346938,
        r: 100,
        color: "bubbleHL",
        link: ["rationals","remainder"],
        title: "Integer Division",
        facts: "We divide using the '/' symbol. Two integers on either side can create a new number. The left side is the 'numerator', and the right side is the 'denominator'. The expression $6 / 2$ is the same as $3$, and integer and natural number. The expression $-8 / 2$ is the same as $-(8 / 2)$, which is the same as $- ( 4 )$, which is the same as $-4$, an integer. What does division mean? It means how often can we subtract the denominator from the numerator until it becomes zero? From 6 we can subtract 2, three times: $6 / 2$ is the same as $3$. The expression $6 - 2 - 2 - 2$ becomes $0$.",
    },
    rationals: {
        x: 188.37755102040956,
        y: -12845.418367346938,
        r: 100,
        color: "bubbleHL",
        link: ["51","49","45"],
        title: "Rationals",
        facts: "Names you must know: <br>\n<strong>Numerator:</strong> The number on top <br>\n<strong>Denominator:</strong> The number on the bottom <br>\n<br>\nYou have seen integer division. What if the subtraction of the denominator from the numerator doesn't go to 0? Remember that with the expression 6 / 2, we subtract the right side from the left side (of the / sign) until the left side is 0. What if we have something like $$\\frac{5}{2}$$ Let's try: $$5 - 2 = 3$$\nNow we have $$3$$\nNext:\n$$3 -  2 = 1$$\n If we subtract 2 once again, we get -1, an integer. So we can not divide the number and get a integer as result. We are left at 1. This (1) is called the remainder. We can create a new type of number. We call this number a 'Rational Number'. It is called rational because it is defined by a ratio of two numbers. The expression $\\frac{5}{2}$ is 2.5 in decimal notation, because the remainder is only half (0.5) that of 2.\n<br><br>\nWe use the symbol\n\n$$ \\mathbb{Q} $$\nto mean \"all rational numbers\".",
    },
    remainder: {
        x: 1586.3726397876217,
        y: -12244.538725734197,
        r: 100,
        color: "bubbleHL",
        link: ["21"],
        title: "Remainder",
        facts: "If you divide a number, you subtract the denominator from the numerator until the numerator is zero. Sometimes, the subtraction hops over the zero. In the expression $7 / 3$, we first subtract via $7 - 3$, which is $4$. Then we subtract via $4 - 3$, which is $1$. Then we subtract via $1 - 3$, which is $-2$. We have hopped over $0$. If we want integer division, we use what we call a 'remainder'. We go back and look at the number that was before the jump over $0$. This was $1$. So we can now say: $7 / 3$ is the same as $2$, with remainder $1$. Why is it $2$? Because we could subtract $2$ times.",
    },
    integer_mul: {
        x: -770.5,
        y: -12187.166666666666,
        r: 100,
        color: "bubbleHL",
        link: [],
        title: "Integer Multiplication",
        facts: "When multiplying two integers (using the $*$ or $\\times$ symbol), you will always get a new integer. $4 \\times 3$ is $12$. Remember, integers can be negative, like $-5$. The expression $-5 \\times 2$ is $-10$, which is an integer. When you multiply negative number, you can move them 'out' of the multiplication: $-5 \\times 2$ can be written as $-(5 \\times 2)$. You can now calculate $5 \\times 2$, which is $10$. You put 10 where $5 \\times 2$ is: $-(10)$. You remove the parentheses, and get $-10$.",
    },
    integers: {
        x: 195.37755102040956,
        y: -11937.418367346938,
        r: 100,
        color: "bubbleHL",
        link: ["rationals","integer_addition"],
        title: "Integers",
        facts: "Remember from 'Natural Numbers' that -1 is not a natural number, because it has a minus sign in the number. When you subtract: $$3 - 4$$ you will not get a natural number. The expression $$3 - 4$$ evaluates to $$-1$$ This is not a natural number. One type of number can create other types of numbers. All natural numbers are also integers, but not all integers are natural numbers.\n<br><br>\nHere is the integer number line.\n\n<img src=\"Textures/integers-numbers-on-number-line.png\">\n\nWe use the symbol $ \\mathbb{Z} $ to mean \"all integer numbers\".",
    },
    natural_multiplication: {
        x: -766.6666666666679,
        y: -11162.833333333332,
        r: 100,
        color: "bubbleHL",
        link: ["144977015948509"],
        title: "Natural Multiplication",
        facts: "Multiplication is an operation on two natural numbers. It always generates a new natural number. It can not create a non-natural number. We use the $*$ or $\\times$ symbol for multiplication. The expression $5 \\times 4$ is the same as the number $20$. The expression can be read as $5 + 5 + 5 + 5$. There are $4$ fives, which are added together. This means that $3 \\times 6$ is the same as $3 + 3 + 3 + 3 + 3 + 3$. This number is $18$.",
    },
    integer_addition: {
        x: -296.62244897959044,
        y: -11989.418367346938,
        r: 100,
        color: "bubbleHL",
        link: ["integer_mul"],
        title: "Integer Addition",
        facts: "Adding integers is very similar to natural numbers. 4 and 5 are both natural numbers as well as integer numbers. Adding them gives 9. This is also a natural number and an integer number. Integers can be negative. This means they have a minus sign in the number. The expression $$5 + -3$$ contains two numbers, $5$, and $-3$. When you see a '+ -', you can replace the '+ -' by just '-'. You then get $$5 - 3$$ which is subtraction. You get\n\n$$2$$\n\nWhen you see $$5 + -3$$ think that you have temperature $5$, and you're adding $3$ ice blocks (because of -, they are cold). The temperature goes down.",
    },
    integral: {
        x: -191.1439356230312,
        y: -17277.96656711465,
        r: 100,
        color: "bubbleHL",
        link: ["44"],
        title: "Integration",
        facts: "$$\\int$$ is the integration symbol, it means \"to sum\" over an infinitesimally small intervals.",
    },
    386721657746765: {
        x: -1222.3485150157694,
        y: -15923.270864443333,
        r: 40,
        color: "bubbleHL",
        link: [],
        title: "Negative base",
        facts: "So we are getting pretty good at exponentiation and powers. It's time to look at negative bases. <br>\nWith integers it fairly easy:\n$$(-3)^4 = (-3) \\times (-3) \\times (-3) \\times (-3) = 81$$\nWait, that's the same as\n$$3^4 = 81$$\nBut with a odd number we get:\n$$(-3)^3 = -27$$\nBut \n$$3^3 = 27$$\nSo the sign will flip for odd integers. <br>\n<br>\nNow the interesting part, decimal power: <br>\n$$(-3)^{2.5}$$\nWell that's just\n$$(-3) \\times (-3) \\times (-3)^{0.5}$$\nBut what is:\n$$(-3)^{0.5}$$ \n? <br>\nFirst you must know <a onclick=\"teleportTo(31);\">Complex numbers</a> <br>\nStay tuned for more\n",
    },
    7817708969890363: {
        x: -132.13364858140358,
        y: -3432.3906587025067,
        r: 100,
        color: "bubbleHL",
        link: ["mouseless"],
        title: "Help",
        facts: "The top-right corner contains a 'H'. Click this to get a quick help menu on shortcuts and keys.",
    },
    4118398304023309: {
        x: -465.1336485814036,
        y: -14372.390658702505,
        r: 100,
        color: "bubbleHL",
        link: [],
        title: "Symbolic Multiplication",
        facts: "When you multiply symbols, and they are the same, you can write them as exponents:\n\n$$ x\\cdot x $$\n\ncollapses into\n\n$$ x^2 $$\n\nLet's try another one:\n\n$$ x\\cdot x \\cdot x $$\n\ncollapse the first two $x$ into\n\n\n$$ x^2 \\cdot x $$\n\nYou can now add the last $x$ to the exponent and get\n\n$$ x^3 $$\n\nYou can do this for any number:\n\n$$ x^{73} \\cdot x $$\n\ncollapses to\n\n$$ x^{74} $$",
    },
    1990676233998147: {
        x: 977.5330180852634,
        y: -14245.057325369176,
        r: 100,
        color: "bubbleHL",
        link: [],
        title: "Symbolic Division",
        facts: "Dividing symbols has some more rules.\n\n$$ \\frac{x}{x} $$\n\nWhat does this collapse into?\n\nLet's try putting 3 into x:\n\n$$ \\frac{3}{3} $$\n\nWe know this collapses into $1$.\n\nAnother number: 4938.034:\n\n$$ \\frac{4938.034}{4938.034} $$\n\nThis also collapses into $1$.\n\nWhat if every number collapses into $1$?\n\nWhat about\n\n$$ \\frac{x}{x^2} $$\n\nThis collapses into\n\n$$ \\frac{1}{x} $$\n\nBecause with dividing, you can cancel out <em>factors</em> that are the same in the numerator and denominator.\n\n<br>\n<br>\n<strong>Trivia:</strong>\n<br>\nDid you know that division by zero is mathematically <em>undefined</em>?",
    },
    1365603668161835: {
        x: 2292.165438858464,
        y: -16822.072490459585,
        r: 100,
        color: "bubbleHL",
        link: [],
        title: "Law of Cosines",
        facts: "The law of cosines works for any triangle.\n<br>\n<strong>Theorem:</strong>\n$$ c^2 + 2\\cdot a \\cdot b \\cdot \\cos(\\gamma) = a^2 + b^2 $$\n<strong>End of Theorem</strong>\n\n<br>\n<img src=\"Textures/Triangle_with_notations.png\">\n<br>",
    },
    4996274113563965: {
        x: 1433.7327857972377,
        y: -16652.205823792923,
        r: 100,
        color: "bubbleHL",
        link: ["5076501542343901","4010120830761315"],
        title: "Unit Circle",
        facts: "To understand geometry, you need to understand the <em>Unit Circle</em>.\n\n<br>\n<br>\n<img src=\"Textures/unit-circle-simple.gif\">\n<br>\n<br>\n\nThe unit circle is a circle around the origin. Any point on the circle has distance $1$ to the origin. It is a perfect circle. Its equation is\n\n$$ x^2 + y^2 = 1 $$\n\nin the Cartesian coordinate system.",
    },
    5076501542343901: {
        x: 1648.1654388584639,
        y: -16998.072490459585,
        r: 100,
        color: "bubbleHL",
        link: ["59","4134109354619697"],
        title: "sine",
        facts: "Sine is a function. It looks like\n\n$$ \\sin(\\theta) $$\n\nWhere $\\theta$ (pronounced \"theta\") is a number.\n<br>\nsin gives you the <em>vertical</em> (y) position on the unit circle for a certain $\\theta$.\n\n<br>\n<br>\n<img src=\"Textures/circle-unit-sct.gif\">\n<br>\n<br>",
    },
    4010120830761315: {
        x: 1854.1654388584639,
        y: -16724.072490459585,
        r: 100,
        color: "bubbleHL",
        link: ["1365603668161835","4134109354619697"],
        title: "cosine",
        facts: "Sine is a function. It looks like\n\n$$ \\sin(\\theta) $$\n\nWhere $\\theta$ (pronounced \"theta\") is a number.\n<br>\nsin gives you the <em>horizontal</em> (x) position on the unit circle for a certain $\\theta$.\n\n<br>\n<br>\n<img src=\"Textures/circle-unit-sct.gif\">\n<br>\n<br>",
    },
    4976277242509039: {
        x: 1381.7327857972377,
        y: -16114.205823792923,
        r: 100,
        color: "bubbleHL",
        link: ["4996274113563965"],
        title: "Cartesian Coordinates",
        facts: "When we graph a function, we tend to use the <em>Cartesian Coordinate System</em>. It looks like the following:\n\n<br>\n<br>\n<img src=\"Textures/cartesian-system.png\">\n<br>\n<br>\n\nA coordinate is denoted as a <em>tuple</em>:\n\n$$ (x, y) $$\n\nWhere $x$ is the position along the x-axis, and $y$ is the position along the y-axis.\n<br>\n<strong>Graphing:</strong>\n<br>\n\nSuppose we wish to draw the function\n$$ f(x) = x + 3 $$\n\nWe first need to create an equation between $x$ and $y$:\n\n$$ y = x + 3 $$\n\nNow, we see that this equation contains two variables. \n\nLet's try putting $x = 2$:\n\n$$ y = 2 + 3 $$\n\nOkay, so in that case, $y = 5$. You see that you can put in any $x$, and you get out a specific $y$.\n\nThe graph shows you what $y$ value you get for a specific $x$. Just follow the $x$ directly up to find its $y$ value.\n\n<br>\n<br>\n<img src=\"Textures/x-plus-3.png\">\n<br>\n<br>\n\n",
    },
    3649384428322541: {
        x: 2246.165438858464,
        y: -17340.072490459585,
        r: 100,
        color: "bubbleHL",
        link: [],
        title: "Law of Tangents",
        facts: "The law of tangents works for any triangle.\n<br>\n<strong>Theorem:</strong>\n$$ \\frac{a-b}{a+b} = \\frac{\\tan(\\frac{1}{2}(\\alpha - \\beta)}{\\tan(\\frac{1}{2}(\\alpha+\\beta))} $$\n<strong>End of Theorem</strong>\n\n<br>\n<img src=\"Textures/Triangle_with_notations.png\">\n<br>\nDoneCancel",
    },
    999093708594227: {
        x: 1751.0089762734278,
        y: -15973.310585697684,
        r: 100,
        color: "bubbleHL",
        link: [],
        title: "Function Arity",
        facts: "A function's <em>arity</em> tells us how many parameters the function has and thus also how many arguments it takes.\n\n$$ f(x) = x^3 $$\n\nIs a function of arity $1$.\n\n$$ g(x, y) = x^3*y $$\n\nIs a function of arity $2$.\n\n$$ g(x, y) = x^3 $$\n\nIs a function of arity $2$. It doesn't matter what the function actually uses, as long as the parameters are listed, they define the function arity.\n\n$$ h(a, b, c, d, e) = 20 $$\n\nHas arity $5$.\n\n$$ k(x) = x*y $$\n\nHas arity $1$.\n\n<br>\n<br>\n<strong>Trivia:</strong>\n<br>\nDid you think that a number can be considered a function of zero arity?",
    },
    2727107890740015: {
        x: 1921.0089762734278,
        y: -14877.310585697684,
        r: 100,
        color: "bubbleHL",
        link: [],
        title: "Bidirectional Implies",
        facts: "You can also imply using a bidirectional implication.\n\n$$\\Leftrightarrow$$\n\nis the symbol we use.\n\nThis means that two expressions lead to the other.\n\n$$ 3 = 1 + 2 \\Leftrightarrow 4 = 1 + 3 $$",
    },
    7310707662813565: {
        x: -1036.9910237265713,
        y: -16285.310585697684,
        r: 100,
        color: "bubbleHL",
        link: ["39"],
        title: "Exponentiation",
        facts: "Exponentiating an irrational number often gives us a new irrational number. Especially if we use decimal powers.\n\n$$ 10^{5.3} $$\n",
    },
    4134109354619697: {
        x: 2058.165438858464,
        y: -17080.072490459585,
        r: 100,
        color: "bubbleHL",
        link: ["3649384428322541","2752534480731885"],
        title: "tangent",
        facts: "The tangent is defined as\n\n$$ \\tan(x) = \\frac{\\sin(x)}{\\cos(x)} $$\n\nIt tells us the steepness of the curve on the circle at a given angle.\n\n<br>\n<br>\n<img src=\"Textures/circle-unit-sct.gif\">\n<br>\n<br>",
    },
    2752534480731885: {
        x: 1538.1654388584616,
        y: -17619.470864443334,
        r: 100,
        color: "bubbleHL",
        link: ["1625136127430609"],
        title: "SOHCAHTOA",
        facts: "An ancient rule of trigonometry is SOH-CAH-TOA.\n\nThis rule will help you remember extremely important identities that you can use to <em>master</em> trigonometry!\n<br>\n<br>\nSOH: Sine is Opposite/Hypotenuse\n$$ \\sin(A) = \\frac{a}{c} $$\n\nCAH: Cosine is Adjacent/Hypotenuse\n\n$$ \\cos(A) = \\frac{b}{c} $$\n\nTOA: Tangent is Opposite/Adjacent\n$$ \\tan(A) = \\frac{a}{b} $$\n\n\n\n\n<br>\n<img src=\"Textures/small-right-triangle-noted.png\">\n<br>",
    },
    1625136127430609: {
        x: 1165.0714285714284,
        y: -17608.54081632653,
        r: 100,
        color: "bubbleHL",
        link: ["7982720977690619"],
        title: "Circular Identity",
        facts: "An important application of the Pythagoream Theorem is the following theorem:\n\n<strong>Theorem:</strong>\n$$ \\sin^2(\\theta) + \\cos^2(\\theta) = 1 $$\n<strong>End of Theorem</strong>",
    },
    7982720977690619: {
        x: 953.0714285714284,
        y: -18044.54081632653,
        r: 100,
        color: "bubbleHL",
        link: ["8479124907529589"],
        title: "Euler's Formula",
        facts: "Euler's formula is the given via the following equation:\n\n$$ \\cos(\\theta) + i\\cdot \\sin(\\theta) = e^{i\\theta} $$",
    },
    3559675231308331: {
        x: 845.0714285714284,
        y: -17484.54081632653,
        r: 100,
        color: "bubbleHL",
        link: ["7982720977690619"],
        title: "MacLaurin Series",
        facts: "The MacLaurin series is an infinite sum of function evaluations to create a polynomial that approximates that function:\n\n$$ \\bar{f}(x) = \\sum^{\\infty}_{n = 0}   \\frac{f^{(n)}(0)}{n!}x^n $$\n\nRemember that $!$ is the factorial.",
    },
    144977015948509: {
        x: -1585.8345611415384,
        y: -12109.470864443334,
        r: 100,
        color: "bubbleHL",
        link: [],
        title: "Factorial",
        facts: "The factorial of a natural number is the product of all previous numbers:\n\nWe use the $!$ symbol to denote the factorial:\n\n$$ 8! $$\n\nTurns into\n\n$$ 8 \\cdot 7 \\cdot 6 \\cdot 5 \\cdot 4 \\cdot 3 \\cdot 2 \\cdot 1 $$\n\nwhich becomes $40320$.",
    },
    8398340884863259: {
        x: 500.76016260162396,
        y: -17236.817073170743,
        r: 100,
        color: "bubbleHL",
        link: ["3559675231308331"],
        title: "Factorial 2",
        facts: "We've already seen factorial under Natural Numbers, but here we give a more precise definition:\n\n$$ k! = \\prod^k_{n=1} n $$",
    },
    5862308996258507: {
        x: 715.7113821138173,
        y: -16604.76016260163,
        r: 100,
        color: "bubbleHL",
        link: ["3559675231308331"],
        title: "Sum",
        facts: "The following symbol is called the sum symbol:\n\n\n$$ \\sum $$\n\nIt is the greek letter 'sigma'. \n\nIn mathematics it is used to define a sum without writing each term.\n\n$$ \\sum^5_{n=1} n $$\n\nexpands to\n\n$$ 1 + 2 + 3 + 4 + 5 $$\n\nWe can apply any operation to the number:\n\n$$ \\sum^5_{n=1} f(n) $$\n\nWill turn into:\n\n$$ f(1) + f(2) + f(3) + f(4) + f(5) $$",
    },
    4419110068750971: {
        x: 312.1625186660003,
        y: -16968.0418948067,
        r: 100,
        color: "bubbleHL",
        link: ["8398340884863259"],
        title: "Product",
        facts: "The following symbol is called the product symbol:\n\n\n$$ \\prod $$\n\nIt is the greek letter 'pi'. \n\nIn mathematics it is used to define a product without writing each factor.\n\n$$ \\prod^5_{n=1} n $$\n\nexpands to\n\n$$ 1 \\cdot 2 \\cdot 3 \\cdot 4 \\cdot 5 $$\n\nWe can apply any operation to the number:\n\n$$ \\prod^5_{n=1} f(n) $$\n\nWill turn into:\n\n$$ f(1) \\cdot f(2) \\cdot f(3) \\cdot f(4) \\cdot f(5) $$",
    },
    5576399967555123: {
        x: -387.0827111332369,
        y: -15319.864526298326,
        r: 100,
        color: "bubbleHL",
        link: [],
        title: "Polynomial Derivative",
        facts: "Deriving polynomials has an easy rule:\n\nFor each term, multiply by the exponent and subtract $1$ from the exponent.\n<br>\n<br>\n<strong>Example:</strong>\n<br>\n$$ f(x) = x^2 $$\n$$ \\Rightarrow f'(x) = 2x $$\n<br>\n<br>\n<strong>Example:</strong>\n<br>\n$$ f(x) = x^5 + 8\\cdot x^3 $$\n$$ \\Rightarrow f'(x) = 5x^4 + 8\\cdot 3 x^2 $$\n",
    },
    93946261109823: {
        x: 1124.947486311597,
        y: -16080.58130081301,
        r: 100,
        color: "bubbleHL",
        link: ["43"],
        title: "Limit",
        facts: "The limit of an expression asks: \"what happens if we approach this value from a certain path?\"\n<br>\nWe write the limit as\n\n$$ \\lim_{x \\rightarrow v} f(x) $$\n\nwhere $v$ is the value we approach, and $f$ is an arbitrary function of $x$.\n<br>\nIntuitively, look at the following graph:\n<br>\n<br>\n<img src=\"Textures/step-function.png\">\n<br>\n<br>\n\nWhat happens if $x$ approaches $0$ from the right? The value is $1$.\n$$ \\lim_{x \\rightarrow 0^+} f(x) = 1 $$\n\nWhat happens if the value is approached from the left? That will be $0$.\n$$ \\lim_{x \\rightarrow 0^-} f(x) = 0 $$\n\nLimits from either side are well defined, but the total limit\n\n$$ \\lim_{x \\rightarrow 0} f(x) = undefined $$\n\n<br>\n<br>\n\nThe following graph, suppose we want to find $ \\lim_{x\\rightarrow -1} f(x) = 2 $.\n<br>\nThe limit is the same from both sides.\n<br>\n<br>\n<img src=\"Textures/x-plus-3.png\">\n<br>\n<br>",
    },
    8479124907529589: {
        x: 1619.242492118783,
        y: -18100.635390741685,
        r: 100,
        color: "bubbleHL",
        link: ["4872400152833709"],
        title: "Cosine Sum",
        facts: "Let's see what we can do with\n\n$$ \\cos(A+B) $$\n\nRemember Euler's formula:\n\n$$\\cos(\\theta) + i\\cdot \\sin(\\theta) = e^{i\\theta}$$\n\nLet's replace $\\theta$:\n\n$$\\Rightarrow \\cos(A+B) + i\\cdot \\sin(A + B) = e^{i\\cdot (A + B)}$$\n\nNow use the identity\n\n$$ e^{A+B} = e^A \\cdot e^B $$\n\n$$ \\Rightarrow \\cos(A+B) + i\\cdot \\sin(A + B) = (\\cos(A) + i\\cdot \\sin(A))\\cdot(\\cos(B) + i\\cdot \\sin(B)) $$\n\n$$ \\Rightarrow \\cos(A+B) + i\\cdot \\sin(A + B) = \\cos(A)\\cos(B) + i\\cdot \\sin(A)\\cos(B) + \\cos(A)\\cdot i\\cdot \\sin(B) - \\sin(A)\\cdot\\sin(B) $$\n\nRealizing that $\\cos$ only returns a real number, we can remove all terms that are imaginary:\n\n$$ \\Rightarrow \\cos(A+B) = \\cos(A)\\cos(B) - \\sin(A)\\cdot\\sin(B) $$\n\nThis identity can be really useful!",
    },
    4872400152833709: {
        x: 1987.242492118783,
        y: -17946.635390741685,
        r: 100,
        color: "bubbleHL",
        link: [],
        title: "Sine Sum",
        facts: "Let's see what we can do with\n\n$$ \\sin(A+B) $$\n\nRemember Euler's formula:\n\n$$\\cos(\\theta) + i\\cdot \\sin(\\theta) = e^{i\\theta}$$\n\nLet's replace $\\theta$:\n\n$$\\Rightarrow \\cos(A+B) + i\\cdot \\sin(A + B) = e^{i\\cdot (A + B)}$$\n\nNow use the identity\n\n$$ e^{A+B} = e^A \\cdot e^B $$\n\n$$ \\Rightarrow \\cos(A+B) + i\\cdot \\sin(A + B) = (\\cos(A) + i\\cdot \\sin(A))\\cdot(\\cos(B) + i\\cdot \\sin(B)) $$\n\n$$ \\Rightarrow \\cos(A+B) + i\\cdot \\sin(A + B) = \\cos(A)\\cos(B) + i\\cdot \\sin(A)\\cos(B) + \\cos(A)\\cdot i\\cdot \\sin(B) - \\sin(A)\\cdot\\sin(B) $$\n\nMultiply both sides by $i$.\n\n\n$$ \\Rightarrow i\\cdot \\cos(A+B) - \\sin(A + B) = i\\cdot\\cos(A)\\cos(B) - \\sin(A)\\cos(B) - \\cos(A)\\cdot \\sin(B) - i\\cdot \\sin(A)\\cdot\\sin(B) $$\n\nRealizing that $\\cos$ only returns a real number, we can remove all terms that are imaginary:\n\n$$ \\Rightarrow \\sin(A+B) = \\sin(A)\\cdot\\cos(B) + \\cos(A)\\cdot\\sin(B) $$\n\nThis identity can be really useful!",
    },
};